name: 'Release Cliq'
description: 'Convert to a Cliq slides template'
inputs:
  webhook:
    description: Webhook URL.
    required: true
  token:
    description: Zoho Cliq zapikey or user webhook token.
    required: true
  sender-name:
    description: Custom sender name for the message.
    required: false
  sender-image:
    description: Custom sender profile picture.
    required: false
  title:
    description: Title of the message.
    required: false
  mode:
    description: Mode
    required: false
  infrastructure:
    description: Infrastructure
    required: false
  version:
    description: Send version message
    required: false
  ref:
    description: Send ref message
    required: false 
    default: main
outputs:
  message-json: 
    description: 'JSON format of the message sent.'
runs:
  using: 'node16'
  main: 'lib/index.js'